name: ${project.artifactId}
main: com.github.exobite.mc.broadcastscheduler.PluginMaster
version: ${project.version}
author: ExoBiTe
website: https://www.spigotmc.org/resources/0/
description: desc.
api-version: 1.17

commands:
  BroadcastScheduler:
    description: BroadcastScheduler Main Command
    usage: /BroadcastScheduler
    aliases: bs

permissions:
  broadcastscheduler.*:
    default: op
    description: All Plugin Permissions
    children:
      broadcastscheduler.notifyOnUpdate: true

  broadcastscheduler.notifyOnUpdate:
    description: Get a Notification upon Login when an Update is available
